/**
 * The above type represents the response data structure for creating a new account.
 * @property {string} response_code - The response code is a string that represents the status of the
 * account creation request. It can be used to determine if the request was successful or if there was
 * an error.
 * @property {string} response_message - The response message is a string that provides information
 * about the result of the account creation process. It can be used to communicate success or failure
 * messages to the user.
 * @property {string} flw_ref - The reference code generated by the payment gateway for the
 * transaction.
 * @property {string} order_ref - The order reference is a unique identifier for the account creation
 * request. It is used to track and identify the specific request made to create the account.
 * @property {string} account_number - The account number associated with the created account.
 * @property {string} frequency - The "frequency" property in the CreateAccountResponseType represents
 * the frequency at which the account is created. It could be daily, weekly, monthly, etc.
 * @property {string} bank_name - The name of the bank where the account was created.
 * @property {string} created_at - The date and time when the account was created.
 * @property {string} expiry_date - The expiry_date property represents the date when the account will
 * expire or become inactive.
 * @property {string} note - The "note" property is a string that can be used to store any additional
 * information or notes related to the account creation response.
 * @property {string} amount - The amount property represents the amount of money associated with the
 * account.
 */
export type CreateAccountResponseType = FLWResponse & {
  data: {
    response_code: string;
    response_message: string;
    flw_ref: string;
    order_ref: string;
    account_number: string;
    frequency: string;
    bank_name: string;
    created_at: Date;
    expiry_date: string;
    note: string;
    amount: string;
  };
};

/**
 * The `CreateBulkAccountResponseType` type represents the response data structure for creating
 * multiple accounts in bulk.
 * @property {string} batch_id - A unique identifier for the batch of accounts that were created.
 * @property {string} response_code - A string representing the response code of the bulk account
 * creation process.
 * @property {string} response_message - The `response_message` property is a string that represents
 * the message or description of the response received after creating a bulk account.
 */
export type CreateBulkAccountResponseType = FLWResponse & {
  data: { batch_id: string; response_code: string; response_message: string };
};

type FetchAccountResponseData = {
  response_code: string;
  response_message: string;
  flw_ref: string;
  order_ref: string;
  account_number: string;
  frequency: string;
  bank_name: string;
  created_at: string;
  expiry_date: string;
  note: string;
  amount: number;
};

/**
 * The FetchAccountResponseType type represents the response data structure for fetching an account.
 * @property {string} response_code - The response code is a string that represents the status of the
 * account fetch request. It can be used to determine if the request was successful or if there was an
 * error.
 * @property {string} response_message - The response message is a string that provides information
 * about the result of the account fetch operation. It can contain details such as success or failure
 * messages, error codes, or any other relevant information.
 * @property {string} flw_ref - The flw_ref property is a string that represents the Flutterwave
 * reference for the account.
 * @property {string} order_ref - The order reference is a unique identifier for the account fetch
 * request. It is used to track and identify the specific request made to fetch the account details.
 * @property {string} account_number - The account number associated with the fetched account.
 * @property {string} frequency - The "frequency" property in the FetchAccountResponseType represents
 * the frequency at which the account is used or accessed. It could indicate how often transactions are
 * made or how frequently the account is checked or updated.
 * @property {string} bank_name - The name of the bank associated with the account.
 * @property {string} created_at - The `created_at` property represents the date and time when the
 * account was created.
 * @property {string} expiry_date - The expiry_date property represents the date when the account will
 * expire or become invalid.
 * @property {string} note - The "note" property is a string that can be used to store any additional
 * information or notes related to the account.
 * @property {number} amount - The amount property is of type number and represents the amount
 * associated with the account.
 */
export interface FetchAccountResponseType extends FLWResponse {
  data: FetchAccountResponseData;
}

export type FetchBulkAccountResponseType = FLWResponse & {
  data: FetchAccountResponseType['data'][];
};
/**
 * The below type represents the payload for creating bulk accounts in TypeScript.
 * @property {string} email - The email property is a string that represents the email address
 * associated with the account.
 * @property {boolean} is_permanent - The `is_permanent` property is a boolean value that indicates
 * whether the account is permanent or not. If it is set to `true`, it means the account is permanent,
 * and if it is set to `false`, it means the account is not permanent.
 * @property {string} bvn - BVN stands for Bank Verification Number. It is a unique identification
 * number issued by the Central Bank of Nigeria to every bank customer in Nigeria. BVN is used to
 * verify and authenticate the identity of bank customers and reduce fraudulent activities in the
 * banking system.
 * @property {string} accounts - The `accounts` property in the `BulkAccountPayload` type represents a
 * string that contains the account numbers. It is used to specify the account numbers for which the
 * bulk account operation is being performed.
 * @property {string} frequency - The `frequency` property is an optional string that represents the
 * frequency at which the account transactions will occur. It is used to specify how often the
 * transactions will be made, such as "daily", "weekly", "monthly", etc.
 * @property {string} tx_ref - The `tx_ref` property is a unique transaction reference that identifies
 * a specific transaction. It is typically used to track and reference the transaction in the system.
 * @property {number} amount - The `amount` property in the `BulkAccountPayload` type represents the
 * amount of money associated with the account. It is of type `number`, indicating a numeric value.
 */
export type BulkAccountPayload = {
  email: string;

  bvn: string;
  accounts: number;

  tx_ref: string;
  amount?: number | null;
};
type FLWResponse = {
  status: 'success' | 'error';
  message: string;
};

/**
 * The above type represents the payload for creating an account, including email, name, BVN,
 * narration, transaction reference, optional amount, and phone number.
 * @property {string} email - A string representing the email address of the account holder.
 * @property {string} firstname - The `firstname` property represents the first name of the account
 * holder.
 * @property {string} lastname - The `lastname` property represents the last name of the account
 * holder.
 * @property {string} bvn - BVN stands for Bank Verification Number. It is a unique identification
 * number issued by the Central Bank of Nigeria to every bank customer in Nigeria. It is used to verify
 * the identity of individuals for banking transactions.
 * @property {string} narration - The "narration" property in the AccountPayload type represents a
 * description or explanation of the transaction. It is typically used to provide additional
 * information about the purpose or nature of the transaction.
 * @property {string} tx_ref - The `tx_ref` property is a unique transaction reference that is used to
 * identify a specific transaction. It is typically generated by the system or application handling the
 * transaction and is used to track and reference the transaction throughout its lifecycle.
 * @property {number} amount - The `amount` property is an optional property of type number. It
 * represents the amount of money associated with the account payload.
 * @property {string} phonenumber - The `phonenumber` property is a string that represents the phone
 * number associated with the account.
 */
export type AccountPayload = {
  email: string;
  firstname: string;
  lastname: string;
  bvn: string;
  narration: string;
  tx_ref: string;
  amount?: number | null;
  phonenumber: string;
};

/**
 * The FetchBulkAccountPayload type represents the payload for fetching bulk accounts, including the
 * batch ID and an optional HTTP method.
 * @property {string} batch_id - A string representing the ID of the batch for which the accounts need
 * to be fetched.
 * @property {'GET' | 'POST' | 'PUT' | 'DELETE'} method - The `method` property is an optional property
 * that specifies the HTTP method to be used for fetching the bulk account payload. It can have one of
 * the following values: 'GET', 'POST', 'PUT', or 'DELETE'.
 */
export type FetchBulkAccountPayload = {
  batch_id: string;
  method?: 'GET' | 'POST' | 'PUT' | 'DELETE';
  excludeQuery?: boolean;
};

/**
 * The FetchAccountPayload type represents the payload for fetching an account, including the order
 * reference, HTTP method, and an option to exclude the query.
 * @property {string} order_ref - The `order_ref` property is a string that represents the reference
 * number of an order.
 * @property {'GET' | 'POST' | 'PUT' | 'DELETE'} method - The `method` property is an optional property
 * that specifies the HTTP method to be used for fetching the account. It can have one of the following
 * values: 'GET', 'POST', 'PUT', or 'DELETE'. If not provided, the default value is 'GET'.
 * @property {boolean} excludeQuery - The `excludeQuery` property is an optional boolean flag that
 * indicates whether or not to exclude the query parameters from the request. If set to `true`, the
 * query parameters will be excluded; if set to `false` or not provided, the query parameters will be
 * included in the request.
 */
export type FetchAccountPayload = {
  order_ref: string;

  excludeQuery?: boolean;
};

export type BvnUpdatePayload = {
  bvn: string;
  order_ref: string;
};

export type BvnResponseDataType = {
  bvn: string;
  first_name: string;
  middle_name: string;
  last_name: string;
  date_of_birth: string;
  phone_number: string;
  registration_date: string;
  enrollment_bank: string;
  enrollment_branch: string;
  'image_base_64?': string;
  address?: string;
  gender: 'Male' | 'Female';
  email?: string;
  watch_listed?: string;
  nationality?: string;
  marital_status?: string;
  state_of_residence?: string;
  lga_of_residence?: string;
  image?: any;
};

export type BvnCheckResponseType = FLWResponse & {
  data: BvnResponseDataType;
};
