/**
 * THE AVAILABLE PERMISSIONS
 */
export enum PermissionsE {
  //CRUD PRODUCT
  CREATE_PRODUCT = "CREATE_PRODUCT",
  VIEW_PRODUCT = "VIEW_PRODUCT",
  EDIT_PRODUCT = "EDIT_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  // CRUD CATEGORY
  CREATE_STAFF = "CREATE_STAFF",
  VIEW_STAFF = "VIEW_STAFF",
  EDIT_STAFF = "EDIT_STAFF",
  DELETE_STAFF = "DELETE_STAFF",
  // CREATE

  //CREATE ROLE
  CREATE_ROLE = "CREATE_ROLE",
  VIEW_ROLE = "VIEW_ROLE",
  EDIT_ROLE = "EDIT_ROLE",
  DELETE_ROLE = "DELETE_ROLE",
  //DISPATCH ROLE

  //SALES

  //SHIPPING FEE MANAGER
}
