// Define enum for jobs
export enum JobTypes {
  GET_CURRENCY_PRICE = 'GET_CURRENCY_PRICE',
  GET_WALLET_BALANCE = 'GET_WALLET_BALANCE',
  PROCESS_WALLET_DEPOSIT = 'PROCESS_WALLET_DEPOSIT',
  PROCESS_WALLET_WITHDRAWAL = 'PROCESS_WALLET_WITHDRAWAL',
}
